umbrella-network/pegasus-feeds

- dev/feeds.yaml
- feeds.yaml
This adds FootballStars' price in comparison to USD.
Related to [OR-682](https://umbnetwork.atlassian.net/browse/OR-682?atlOrigin=eyJpIjoiZjhjN2UxMDUyZWUwNDgwOWIxNDc5Yjg3NjVhZTEzZDAiLCJwIjoiaiJ9)
> Feature / Add FTS-USD price

- .gitignore
- prod/bsc/feeds.yaml
- prod/bsc/feedsOnChain.yaml
- prod/eth/feeds.yaml
- prod/eth/feedsOnChain.yaml
I kept old once for now, so the change will be smooth
> chore: production feeds by blockchain

- dev/bsc/feeds.yaml
- dev/bsc/feedsOnChain.yaml
- dev/eth/feeds.yaml
- dev/eth/feedsOnChain.yaml
This adds a new pair to the development environment.
> feature: DAI-BNB on dev

- prod/bsc/feeds.yaml
The address for Validator Registry was wrong. Fixed it.
> fix: Change BSC registry address [prod]

- feeds.yaml
- prod/bsc/feeds.yaml
- prod/eth/feeds.yaml
> feature: Add INT-USD [prod]

- dev/bsc/feeds.yaml
- dev/eth/feeds.yaml
This adds KaikoPriceStream for every FIAT pair.
> feature: Kaiko Fetcher [dev]

- dev/bsc/feeds.yaml
- dev/eth/feeds.yaml
Adds configs to Options fetcher
> feature: Options config [dev]

- dev/eth/feedsOnChain.yaml
Added a WHEY-USD fetcher to ETH Dev (Kovan)
> feat: Add WHEY-USD on Kovan

- dev/bsc/feedsOnChain.yaml
> feature: Add WHEY-USD feed

- dev/bsc/feeds.yaml
This changes the label from the OPTIONS configuration to "OP:(ASSET)-*".
> fix: Options labeling [dev]

- prod/bsc/feeds.yaml
> feature: Options config [prod]

- dev/bsc/feeds.yaml
- dev/eth/feeds.yaml
Remove MATTER-USDT feed from BSC and ETH in dev
> feat: Remove MATTER-USDT [dev]

- feeds.yaml
- prod/bsc/feeds.yaml
- prod/eth/feeds.yaml
Added UFT-USD feeds for BSC and ETH
> feat: Add UFT-USD [prod]

- prod/bsc/feeds-5.5.yaml
- prod/bsc/feeds.yaml
Adds Options and Yearn feeds to Prod BSC.
**Note:** The `feeds-5.5.yaml` file is temporary and shall be removed in the future. We had to create it just for pegasus version 5.5.0. That way, we avoid older versions from breaking.
> feature: Add versioned feeds file [prod]

- prod/bsc/feeds-5.5.yaml
Activates Yearn feeds in prod.
> feature: Activate Yearn [prod]

- prod/bsc/feeds.yaml
> feature: kft-usd and fuse-usd [prod]

- prod/bsc/feeds.yaml
> feature: SNP-USD as L2D [prod]

- feeds.yaml
Coingecko link:
https://www.coingecko.com/en/coins/mahadao
> feat: add MAHA_USD in PROD

- backup/feeds-5.5-backup.yaml
- backup/feeds-backup.yaml
- backup/prod/feeds.yaml
- dev/bsc/feeds.yaml
- package-lock.json
- package.json
- src/backupFeeds.ts
- src/countFeeds.ts
- src/feeds.ts
- src/updateEquityFeeds.ts
- src/utils/feedsUtils.ts
updated feeds.yaml to have 2481 equity symbols, which includes all symbols that were currently in prod + russel 2000
> Develop add feeds test

- dev/bsc/feedsOnChain.yaml
Removes feeds that are no longer used and are still commented in the file.
> chore: Remove commented feeds

- backup/feeds-backup.yaml
- backup/prod/feeds.yaml
- dev/bsc/feeds-5.5.yaml
- dev/bsc/feeds.yaml
> feature: Add MNY-USD as L2D

- prod/bsc/feeds.yaml
- prod/bsc/feedsOnChain.yaml
Add MAHA-USD on L2D, because all data that are on de FCD has to be on the L2D.
Change DAI-USD FCD to have precision 3 like DAI-USD on L2D.
> [prod] fix: Remove differences between feeds and feedsOnChain

- prod/bsc/feeds.yaml
> ARTH-USD with discrepancy 0.5%

- prod/onChainData128.8.yaml
Remove WBTC-USD as onchain data.
> Remove WBTC-USD

- prod/onChainData128.8.yaml
Scale down ETH-USD and USDT-USD on Linea.
> Scale down Linea

- dev/onChainDeviation128.8.yaml
Replace individual gold feeds used to test fetchers by a consoldiated GOLD-USD feed using all three fetchers.
> Add consolidated GOLD-USD feed to dev

- sbx/onChainDeviation128.8.yaml
Changes to be able to asses avg tx cost on Rootstock testnet
> Update Rootstock conf onChainDeviation128.8.yaml

- sbx/onChainDeviation128.8.yaml
Add support to GOLD-USD and BTC-USD for Midas in sbx. Remove crvUSD-USD
> Update feeds in onChainDeviation128.8.yaml

- dev/onChainDeviation128.8.yaml
> remove Gold price from dev

- dev/onChainDeviation128.8.yaml
Reverts umbrella-network/pegasus-feeds#221
> Revert "comment feeds not in sovryn"

- prod/onChainData128.8-validator1.yaml
this is copy of general file + new names
> use new fetcher names

- prod/onChainData128.8-validator1.yaml
- prod/onChainData128.8.yaml
- Correct feeds required for 5ire
- Correct feeds for Massa
> Add feeds for 5ire
